// Code generated by sqlc-grpc (https://github.com/walterwanderley/sqlc-grpc). DO NOT EDIT.

package author

import (
	"google.golang.org/protobuf/types/known/wrapperspb"

	pb "my/api/author/v1"
)

func toAuthor(in Author) *pb.Author {

	out := new(pb.Author)
	out.Id = in.ID
	out.Name = in.Name
	if in.Bio.Valid {
		out.Bio = wrapperspb.String(in.Bio.String)
	}
	out.CompanyId = in.CompanyID
	if in.Size.Valid {
		out.Size = wrapperspb.Int64(in.Size.Int64)
	}
	if in.EmptyCol.Valid {
		out.EmptyCol = wrapperspb.Int32(in.EmptyCol.Int32)
	}
	out.DefaultCol = in.DefaultCol
	if in.Size1.Valid {
		out.Size1 = wrapperspb.Int32(in.Size1.Int32)
	}
	out.DefaultCol1 = in.DefaultCol1
	out.Type = string(in.Type)
	out.Type1 = string(in.Type1)
	return out
}
