// Code generated by sqlc-grpc (https://github.com/walterwanderley/sqlc-grpc).

package author

import (
	"go.uber.org/zap"

	pb "my/api/author/v1"
)

// NewService is a constructor of a pb.AuthorServiceServer implementation.
// Use this function to customize the server by adding middlewares to it.
func NewService(logger *zap.Logger, querier *Queries) pb.AuthorServiceServer {
	return &Service{logger: logger, querier: querier}
}
