// Code generated by sqlc-grpc (https://github.com/walterwanderley/sqlc-grpc). DO NOT EDIT.

package main

import (
	"database/sql"

	"go.uber.org/zap"
	"google.golang.org/grpc"

	pb_author "my/api/author/v1"
	app_author "my/internal/author"
	"my/internal/server"
)

func registerServer(logger *zap.Logger, db *sql.DB) server.RegisterServer {
	return func(grpcServer *grpc.Server) {
		pb_author.RegisterAuthorServiceServer(grpcServer, app_author.NewService(logger, app_author.New(db)))

	}
}

func registerHandlers() []server.RegisterHandler {
	var handlers []server.RegisterHandler

	handlers = append(handlers, pb_author.RegisterAuthorServiceHandler)

	return handlers
}
