// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: clientStructure.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Client struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email   string         `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Country string         `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Inbox   []*Client_Mail `protobuf:"bytes,5,rep,name=inbox,proto3" json:"inbox,omitempty"`
}

func (x *Client) Reset() {
	*x = Client{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientStructure_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_clientStructure_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_clientStructure_proto_rawDescGZIP(), []int{0}
}

func (x *Client) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Client) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Client) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Client) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Client) GetInbox() []*Client_Mail {
	if x != nil {
		return x.Inbox
	}
	return nil
}

type Client_Mail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemoteEmail string `protobuf:"bytes,1,opt,name=remoteEmail,proto3" json:"remoteEmail,omitempty"`
	Body        string `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *Client_Mail) Reset() {
	*x = Client_Mail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clientStructure_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Client_Mail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client_Mail) ProtoMessage() {}

func (x *Client_Mail) ProtoReflect() protoreflect.Message {
	mi := &file_clientStructure_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client_Mail.ProtoReflect.Descriptor instead.
func (*Client_Mail) Descriptor() ([]byte, []int) {
	return file_clientStructure_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Client_Mail) GetRemoteEmail() string {
	if x != nil {
		return x.RemoteEmail
	}
	return ""
}

func (x *Client_Mail) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_clientStructure_proto protoreflect.FileDescriptor

var file_clientStructure_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc4,
	0x01, 0x0a, 0x06, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x28, 0x0a,
	0x05, 0x69, 0x6e, 0x62, 0x6f, 0x78, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x61, 0x69, 0x6c,
	0x52, 0x05, 0x69, 0x6e, 0x62, 0x6f, 0x78, 0x1a, 0x3c, 0x0a, 0x04, 0x4d, 0x61, 0x69, 0x6c, 0x12,
	0x20, 0x0a, 0x0b, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_clientStructure_proto_rawDescOnce sync.Once
	file_clientStructure_proto_rawDescData = file_clientStructure_proto_rawDesc
)

func file_clientStructure_proto_rawDescGZIP() []byte {
	file_clientStructure_proto_rawDescOnce.Do(func() {
		file_clientStructure_proto_rawDescData = protoimpl.X.CompressGZIP(file_clientStructure_proto_rawDescData)
	})
	return file_clientStructure_proto_rawDescData
}

var file_clientStructure_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_clientStructure_proto_goTypes = []interface{}{
	(*Client)(nil),      // 0: proto.Client
	(*Client_Mail)(nil), // 1: proto.Client.Mail
}
var file_clientStructure_proto_depIdxs = []int32{
	1, // 0: proto.Client.inbox:type_name -> proto.Client.Mail
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_clientStructure_proto_init() }
func file_clientStructure_proto_init() {
	if File_clientStructure_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_clientStructure_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Client); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_clientStructure_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Client_Mail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_clientStructure_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_clientStructure_proto_goTypes,
		DependencyIndexes: file_clientStructure_proto_depIdxs,
		MessageInfos:      file_clientStructure_proto_msgTypes,
	}.Build()
	File_clientStructure_proto = out.File
	file_clientStructure_proto_rawDesc = nil
	file_clientStructure_proto_goTypes = nil
	file_clientStructure_proto_depIdxs = nil
}
